### ISSUE TITLE
Webservice: GenerateDOI

### ISSUE THREAD

**Issue by mikeydrew** [ices-tools-dev/DOI#10]
New parameters have been added for resource type general and resource type. New version of the service has been published here -> 

http://doitest.ices.local/api/generateDOI?ns=xx&usr=Mike&url=http://ices.dk&meta=test&resTypeGen=Text&resType=Report

Now ready for further testing through SharePoint etc. 
If meta is defined as test, then a test XML document is used from the server, with the relevant attributes and values added). 
Users (usr) have to be valid and have the required permissions.

**Comment by neil-ices-dk** [comment]
@Nas-ICES-IT Now ready for further testing through SharePoint etc

**Comment by Nas-ICES-IT** [comment]
I have implemented test version on Publication now.... 

![image](https://user-images.githubusercontent.com/38248617/41847466-5daf852c-787a-11e8-9507-5fbcef443666.png)

New menu item with text "DOI version test" is added and when we click to that one will generate DOI by using new Web services.....

**Comment by Nas-ICES-IT** [comment]
Menu item Generate DOI still work on same way with old system....

**Comment by mikeydrew** [comment]
Published and tested new version pointing to Production SQL Server - SQL08 @Nas-ICES-IT, we can go live :)

**Comment by mikeydrew** [comment]
Next step, to update the SharePoint action link ‘Generate DOI’ so that it points to the new URL

**Comment by neil-ices-dk** [comment]
@Nas-ICES-IT Nas to debug issue with DOI postback

**Comment by Nas-ICES-IT** [comment]
Debugged and fixed the problem

**Comment by HansMJ** [comment]
Great!

I just checked at Datacite and the metadata is there. Author = ICES

https://doi.datacite.org/clients/dk.ices/dois?client-id=dk.ices&query=10.17895%2Fices.pub.4513&sort=relevance

Login DK.ICES (fromICES2meta).

☺ Hans
