### ISSUE TITLE
Deactivate disputed DOI's

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#12]
@HansMJ please can you deactivate the following DOI's in DataCite:

10.17895/ices.pub.2861 OSPAR 2017
10.17895/ices.pub.2860 HELCOM 2017

Thanks, Neil

**Comment by HansMJ** [comment]
The 2 DOI’s are deactivated now. There will be a delay before the change is online, but it should happen within a day or so I think.
Hans

**Comment by neil-ices-dk** [comment]
Thanks Hans ☺

**Comment by neil-ices-dk** [comment]
Waiting for a reply @HansMJ to chase up
