### ISSUE TITLE
Webservice: UpdateDoi

### ISSUE THREAD

**Issue by mikeydrew** [ices-tools-dev/DOI#13]
New webservice to be used when updating the meta data and URL for a previously minted DOI in DataCite. This webservice provides the ability to synch SharePoint, Local DB and DataCite. Tested in Dev and now published for production database SQL08 DOI_V2.
Example of the URL to be used ->

http://doitest.ices.local/UpdateDoi?doi=10.5072/ices.xx.4432&usr=mike&url=http://ices.dk/test.test.test.aspx&meta=test&resTypeGen=Service&resType=Report

**Comment by mikeydrew** [comment]
Next step, add a new SharePoint action link to allow the updating of previously minted DOIs. This will be used by Silvia when synching meta data / URLs between SharePoint, local DB and DataCite.

**Comment by Nas-ICES-IT** [comment]
Implemented and live now on production server.. 

![image](https://user-images.githubusercontent.com/38248617/45623740-9c930700-ba88-11e8-8b43-f0e417f076e8.png)
