### ISSUE TITLE
Is affiliation = ICES in metadata correct?

### ISSUE THREAD

**Issue by HansMJ** [ices-tools-dev/DOI#14]
Just to check if this is correct/intended. Note that affiliation is not manadatory in the DataCite schema...
`
<creators> 
    <creator> 
      <creatorName>Roland Cormier; Michael Elliott; and Andreas Kannen</creatorName>  
    <affiliation>ICES</affiliation> 
</creator>
 `

**Comment by CelineByrne** [comment]
Hi Hans

ICES should not be there – I think ICES has been included as the default author if the author field is not filled in.

**Comment by HansMJ** [comment]
Thanks Celine
ICES is not inserted as Author, only the 3 names in this case. But their Affiliation is set to  ICES. This might be OK, I just can’t remember having decided on this.
Hans
