### ISSUE TITLE
Webservice: ReserveDOIs

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#3]
Note: to delete reservd DOI's, will need to do it via admin (Hans)
•	Reserve DOI
o	User that is reserving/requesting DOI is the [user] that needs to be inserted in local DOI DB
o	Input = user, no of DOI's needed (to start we will limit to 100)
o	Output = list of reserved DOI's

**Comment by mikeydrew** [comment]
@neil-ices-dk @HansMJ dev version deployed here -> http://doitest.ices.local/reservedois/xx/mike/10 
params required are namespace/username/number of dois

**Comment by HansMJ** [comment]
Looking great Mike ☺

**Comment by neil-ices-dk** [comment]
@mikeydrew shouldn't only validated users be able to reserve? i tried with /xx/roger/5 and it worked - assuming we don't want Roger to be able to do this ;)

**Comment by mikeydrew** [comment]
@neil-ices-dk  Try again Roger, I dare you ;)  

We need to have a chat about authentication/authorisation and can pick this up at the meeting next week.

**Comment by neil-ices-dk** [comment]
Thanks Mike - yes you're right it might be overkill but we need to see what is sensible - this will (i assume) be a local service only so it's not a major external issue but i can still impersonate another ICES user if i wanted http://doitest.ices.local/reservedois/xx/hans/5 but maybe we just expect that the average user will not be a problem ;)
