### ISSUE TITLE
Webservice: QueryDOI

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#4]
o	Input = DOI, or since [CreateDate] 
o	Output = list of DOI's, ResourceTypeGeneral, Local status, Datacite status

**Comment by mikeydrew** [comment]
Datacite API https://api.datacite.org/works/10.17895/ices.pub.4127

**Comment by neil-ices-dk** [comment]
@Nas-ICES-IT and @mikeydrew we have an issue with the author tag as it takes the username i.e. 'michala' which is nonsensical externally; so we will either have to generalise and take out specific ICES Sec names - or use their full name?

**Comment by neil-ices-dk** [comment]
@mikeydrew to think about the most sensible way to architect this from the perspective of local/datacite information syncing

**Comment by mikeydrew** [comment]
New service created to query local database for DOI info. Deployed here -> 
http://doitest.ices.local/QueryDoi/10.17895/ices.pub.4140

**Comment by mikeydrew** [comment]
New version of web app deployed for DOI querying. Consumes the above local service and datacite service. http://doiweb.ices.local/Manage/query.aspx
![image](https://user-images.githubusercontent.com/10516840/41460889-59298d34-708e-11e8-9106-6ac96baa1ea8.png)
Can also consume SharePoint services to get the DOI meta data, but would need @Nas-ICES-IT to create an index on the DOI/URI as there are over 5000 items in the list. 
http://www.ices.dk/sites/pub/_api/lists/getbytitle('publication%20reports')/items

**Comment by neil-ices-dk** [comment]
it works - now you just need to explain the logic - will pop by

**Comment by neil-ices-dk** [comment]
@mikeydrew to make a query/report that will check for differences between local/Datacite metadata and then this can be used by Silvia to update the ones that are different

**Comment by mikeydrew** [comment]
Published and tested new version pointing to Production SQL Server - SQL08
