### ISSUE TITLE
WebGUI: Sharepoint

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#5]
•	Will be in Sharepoint and will exclusively use the services #4 and #3 
•	.Net application

**Comment by Nas-ICES-IT** [comment]
• .Net application (To reserve DOI number advance) will be separate then SharePoint GUI,  
Mike is doing it with Services API already

**Comment by neil-ices-dk** [comment]
i think that was what i was saying in the start of the thread - let's just clarify when we meet next week
