### ISSUE TITLE
Web app 'ManageDOI'

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#8]
this links to all the service tasks

**Comment by neil-ices-dk** [comment]
Can you add me as a user please :)

**Comment by mikeydrew** [comment]
New version published with the following enhancements :- 

http://doiweb.ices.local/Manage/Reserve.aspx
http://doiweb.ices.local/Manage/Users.aspx

1. Reserved DOIs can now be exported to csv file
2. Validation added to inputs
3. New tab showing all reserved DOIs for the current user 

![image](https://user-images.githubusercontent.com/10516840/40783229-1986caf0-64e2-11e8-9c7c-6889bb9d9782.png)

**Comment by neil-ices-dk** [comment]
nice MikeyD

**Comment by neil-ices-dk** [comment]
further development on #4
